name: Build and Push to ACR

on:
  workflow_dispatch:  # Isse tum manually GitHub se trigger kar sakte ho

permissions:
  id-token: write
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: todo-ui
      IMAGE_TAG: v1
      ACR_NAME: todoazureacr1
      ACR_LOGIN_SERVER: todoazureacr1.azurecr.io
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 669b9585-949d-47fc-bad6-15e843d919a8
          tenant-id:  7e203e7f-46ff-4cc1-8e94-c0903765687e
          subscription-id: 42ef39d4-890a-43c3-9c88-fc38b8fb9943

      - name: Log in to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Tag Docker Image for ACR
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image to ACR
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
